server:
  shutdown: GRACEFUL
  port: 8081

spring:
  application:
    name: primefaces-example
  devtools:
    restart:
      enabled: true

joinfaces:
  faces-servlet:
    enabled: true
  faces:
    project-stage: Development
    facelets-refresh-period: 1
    config-files:
      - /WEB-INF/faces-config.xml
  primefaces:
    theme: aristo
    font-awesome: true

logging:
  level:
    org.joinfaces: DEBUG
    jakarta.faces: DEBUG
