server:
  shutdown: GRACEFUL
  port: 8081

spring:
  application:
    name: primefaces-example
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .xhtml

joinfaces:
  faces:
    project-stage: Development
    facelets-refresh-period: 1
    config-files:
      - /WEB-INF/faces-config.xml